### ISSUE TITLE
some bozo_exceptions doesn't have 'getMessage' attribute

### ISSUE THREAD

**Issue by noahzark** [lordfriend/Albireo#148]
I got several exceptions adding feed:
 
server:94 'BadStatusLine' object has no attribute 'getMessage'

2019/04/01 20:17:32 feed:96 <urlopen error timed out>
2019/04/01 20:17:32 server:94 'URLError' object has no attribute 'getMessage'
https://sentry.io/share/issue/821c2274089f43cc8f4b5e61d28a90b7/
https://sentry.io/share/issue/c668a7a520ca45c2a4dd091f1c74089c/

it seems some bozo_exceptions collected by feedparser doesn't have a getMessage() method

**Comment by lordfriend** [comment]
Oh! that's strange. maybe some network error create this issue.

By the way I find my implementation for Dmhy scrapper has some flaw which may cause Dmhy ban UserAgent of the scrapper. If you find your UA is banned by Dmhy, try to use libyk which also has a dmhy source

**Comment by noahzark** [comment]
k, got it. im using a http proxy and set the interval to around 60m, the scrapper is working now
thank you so much :)

**Comment by lordfriend** [comment]
I'm currently working on a new architecture for this project. but it will take some time to finish and replace the current code.
