### ISSUE TITLE
Add Telegram bot

### ISSUE THREAD

**Issue by lordfriend** [lordfriend/Albireo#15]
The design philosophy of Albireo is automatically complete everything. So the less human operation the better of the system is. What we need here is to notify the end user or the management team an episode is downloaded when it is done. This also help the busy user remember keeping up the progress of a bangumi because most bangumi updates weekly.

Telegram is a really nice im software which I think most of our users have already used that. And it also provides a set of powerful API to achieve this feature.

**Here are the specification**
- The bot will only notify the user if the user authorize the Albireo to notify him/her.
- The bot will only notify the user when the bangumi is being watched by the user
- The bot will only notify the user when not in the slient time
- Notification message should contains a Link to the episode-detail page.

**Comment by noahzark** [comment]
Maybe the chrome push notifications would be more convenient than a Telegram bot? 
https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/

**Comment by lordfriend** [comment]
@noahzark The purpose of using a Telegram bot is let user know a bangumi update even he/she is not visiting this site.

**Comment by kslr** [comment]
Well, need to run telegram bot at the same time (someone doing it?

**Comment by lordfriend** [comment]
This Feature will be considered after user-center feature complete  which is currently under development in user-center branch

**Comment by kslr** [comment]
OK, if needed I can help.

**Comment by kxxoling** [comment]
1. Add telegram username in user-center;
2. Say anything to suki_bot will save the chat_id of conversation, and bind it to related user;
3. Send message when new bangumi is ready.

What you need:

1. Register a new bot.
2. Add a send_message hook when bangumi updates.
3. A telegram bot background process to handle incoming telegram messages.

**Comment by lordfriend** [comment]
@kxxoling Maybe we just need add a communication interface (e.g. RPC) for external process to invoke and  receive messages. then make a new project for telegram bot and run as a individual process.
All settings can be done at telegram. no web UI change is involved.

**Comment by kxxoling** [comment]
How to connect suki user and Telegram ID?

**Comment by lordfriend** [comment]
I don't know the requirements of telegram bot. Maybe an UI change is needed. But what if an user add telegram id which is not his/her id in user-center. Do we have some methods to check the ownership?

**Comment by kxxoling** [comment]
In my assumption, when you add your telegram username in the user pane, it's an unauthed connection. When you contact suki_bot in telegram, the bot app will check the database which user have saved the same telegram username as it is the in coming message.

If you want all the steps happens in telegram, you need to provide something to prove you have the control of which suki account, eg. username and password. I thought it may be not safe to transfer raw password through chat.

**Comment by kxxoling** [comment]
A fake implementation could be like this:

```py
import telegram
from telegram.ext import Updater
from telegram.ext import CommandHandler
from suki.models import User


token = "your_id:your_token"
updater = Updater(token=token)
bot = telegram.Bot(token=token)

def start(bot, update):
    chat_id = update.message.chat_id
    message = update.message.text
    username, password = message.split(':')  # eg your text is in form of `username:password`
    user = User.find_one(username=username)
    if user and user.check_password(password):
        # Save the chat_id and telegram_id to database
        user.telegram_id = update.message.id
        text = "Congratulations! You have successfully connected with %s@suki.moe" % user.username
    else:
        text = "User auth failed, please try again!"
    bot.send_message(chat_id=chat_id, text=text)


start_handler = CommandHandler('start', start)
updater.dispatcher.add_handler(start_handler)

# Multi-process serving for telegram messages.
updater.start_polling()
updater.idle()
```

**Comment by lordfriend** [comment]
This feature request is partially implemented via the new Web Hook feature, which means any developer can make their own push application. including telegram bot.
For web hook feature guide, Read the [Wiki](https://github.com/lordfriend/Albireo/wiki/Web-Hook-Guide).
I also wrote an [example](https://github.com/lordfriend/MailHook) which can send mail to user when special event received.
