### ISSUE TITLE
添加番组，保存失败

### ISSUE THREAD

**Issue by nKsnC** [lordfriend/Albireo#167]
重现步骤：  
1. 添加番组，搜索`化物语`，确认保存
2. 返回500

原因是图片没有成功get，返回错误`ConnectionError: ('Connection aborted.', BadStatusLine("''",))
`

此处需要错误捕获和启用https

联动上游issue https://github.com/bangumi/api/issues/57

**Comment by lordfriend** [comment]
Thx for report this bug. will fix soon
