### ISSUE TITLE
Unable to deploy on a Windows machine?

### ISSUE THREAD

**Issue by noahzark** [lordfriend/Albireo#34]
Tried to use Albireo on a PC, but got stuck with the databases.

I installed all the dependencies, and latest [mysql server for Windows](https://dev.mysql.com/downloads/installer/)

But when I tried to init the database(python tools.py --db-init), an exception is always raised:
```
File "D:\Workspace\python2.7\lib\site-packages\psycopg2\__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) expected authentication request from server, but received
```

this exception is also raised when I try to start the server directly. ( python server

Also I've tried to test the connection using:
```
import psycopg2
conn = psycopg2.connect(database='albireo', user='postgres', password='123456', host='localhost', port='5550')
```
It also comes up with the same problem.

But when I try to test the connection using [MySQL Workbench](https://www.mysql.com/products/workbench/), I'm able to login and the connection is good. So the username/password/port should be good, and SSL is not enabled.

Can you help me with it? Or has anyone successfully deployed Albireo on a PC?

P.S. My installed module versions are:
SQLAlchemy v1.1.5 (I also tried 1.0.0
psycopg2 v2.6.2

**Comment by lordfriend** [comment]
This project is designed working as a server on linux, I did not test on windows. But it maybe work.

The main problem is you are using MySQL but we only support PostgreSql as database because we use some dialects (such as postgresql UUID as primary key).

**Comment by noahzark** [comment]
Oh got it, sorry I didn't read the README carefully. The web server starts normally after PostgreSQL is installed and congfigured. But the services are not running as expected due to the file system difference between Unix and Windows. I'll try to fix it by myself, then submit a pull request OR into another branch (like Windows Ver or something else

Thank you so much for your help and effort on the project
