### ISSUE TITLE
How to turn on scheduled tasks ?

### ISSUE THREAD

**Issue by kslr** [lordfriend/Albireo#41]
My understanding:

Automatic scanning rss found new resources on -> deluge download -> store information

But the Scheduler document says "You need to add some keywords in the admin bangumi detail page for the site you want scan."

Then need to manually add keywords? "Admin bangumi detail page" What does it mean?

**Comment by lordfriend** [comment]
This server contains two parts: An http server that interacts with client (e.g. Deneb), An Scheduler that executes some job periodically at a special interval which can be configured. 

I'm sorry for lacking document of the scheduler part.

The scheduler start several scanner. one of the main scanner is the rss site scanners which are some class inherit from BangumiScanner (Actually is a abstract class). like DmhyScanner, BangumiMoeScanner. These scanner will read `bangumi` table and find that bangumi which has episode need to download and only search specific rss site when that bangumi has a keyword in that site column.

These operation can be done at the client, currently only Deneb has admin interface.
you only need to start server and scheduler, and add bangumi from admin interface. they will do the reset jobs

**Comment by kslr** [comment]
@lordfriend 
thanks for the answer.
It is recommended to add this to readme, can help more people.
