### ISSUE TITLE
Collection of animation distribution lists provide data sources

### ISSUE THREAD

**Issue by kslr** [lordfriend/Albireo#46]
I noticed that BANGUMI.MOE/DMHY/acg.rip provided rss.
If you join a module to collect this information, and provide regular expression syntax search will be better?

But I'm not too familiar with python, I might use javascript. Module or API  :sparkles:	

How do you think about it?

**Comment by kslr** [comment]
- single file Scrapy spider written to postgresql. 
- Increase the regular expression match in the management

**Comment by lordfriend** [comment]
At the early version of this project, only DMHY is supported an admin user must provide a rss url (which is the dmhy rss search url) and an regular expression to make a match, so the scanner can choose the right torrent for corresponding episode. But then at practice we observe that regular expression is easy to miss some result if the title changes a little and also very easy to make some wrong match if provided regular expression is too simple. 

So the next version remove this support.

We have some discussion about allow administrator use a regular expression as higher priority rule to the default (which is actually an regular expression too). But this requirement is not very urgent.

**Comment by kslr** [comment]
Yes, according to the title to do Chinese word segmentation, similar to BANGUMI.MOE design.
I will consider developing this project to test usability.
