### ISSUE TITLE
Add support for episode "variant"

### ISSUE THREAD

**Issue by KTachibanaM** [lordfriend/Albireo#59]
I'd like to add support for scrapping, storing and displaying "variants" of an episode, e.g. "raw-meat" (no subtitle), Chinese-subtitled, Chinese-Japanese subtitled, etc.
The model should be generic enough so that the available variants are not hard-coded but flexible.

**Comment by lordfriend** [comment]
Is the term *variants* means the video type? Currently video information is stored in `video_file` table and can be multiple for a certain episode. I think the *variants* in your example is actually a characteristic for a video file.
So you can use a field label (https://github.com/lordfriend/Albireo/blob/master/domain/VideoFile.py#L24 currently is reserved for similar purpose). the only things we need is update our web client to support modifying this field. and add multiple video for one episode support in clients of all platform.
The episode is basically a description for a bangumi. Keep it simple is a better choice.

**Comment by KTachibanaM** [comment]
Agree. There shouldn't be a change in Albireo but only in Deneb.
