### ISSUE TITLE
Add tracker info to magnet of bangumi.moe

### ISSUE THREAD

**Issue by lordfriend** [lordfriend/Albireo#81]
currently magnet URI from bangumi.moe search API has only hash. this results the torrent with no trackers info too. Sometimes it can be extremely slow to download a torrent which has no tracker info.

A solution is analyzing the magnet URI and append the missing part which is a fixed set of trackers. and use  the complimented magnet URI to download the torrent.

**Comment by kslr** [comment]
such as nayy?

**Comment by lordfriend** [comment]
what's nayy?
